---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "xterm"
    - "gnome-terminal"
    - "vlgothic*-fonts"
    - "ipa*-fonts"
    - "@x11"
    - "@legacy-x"
    - "@internet-browser"
    - "@input-methods"
    - "@fonts"
    - "@emacs"

- name: Update font cache
  command: fc-cache -fv
  register: output

- name: Change window manager
  replace:
    path: "{{ item }}"
    regexp: 'twm'
    replace: 'mwm'
    backup: yes
  with_items:
    - /etc/X11/xinit/Xclients
    - /etc/X11/xinit/Xsession
    - /etc/X11/xinit/xinitrc

- name: Set ibus variables
  copy:
    src: ibus.sh
    dest: /etc/profile.d/ibus.sh
    owner: root
    group: root
    mode: 0644
