---
- name: Install packages
  become: True
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "xterm"
    - "gnome-terminal"
    - "vlgothic*-fonts"
    - "ipa*-fonts"
    - "@x11"
    - "@legacy-x"
    - "@internet-browser"
    - "@input-methods"
    - "@fonts"
    - "@emacs"

- name: Install additional packages for CentOS 6
  become: True
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "xorg-x11-apps"
    - "openmotif"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Update font cache
  become: True
  command: fc-cache -fv

- name: Change window manager from twm to mwm
  become: True
  replace:
    path: "{{ item }}"
    regexp: 'twm'
    replace: 'mwm'
    backup: yes
  with_items:
    - /etc/X11/xinit/Xclients
    - /etc/X11/xinit/Xsession
    - /etc/X11/xinit/xinitrc

- name: Set ibus variables
  become: True
  copy:
    src: ibus.sh
    dest: /etc/profile.d/ibus.sh
    owner: root
    group: root
    mode: 0644

- name: Deploy xinitrc skeleton
  become: True
  copy:
    src: xinitrc.sh
    dest: /etc/skel/.xinitrc
    owner: root
    group: root
    mode: 0644

- name: Deploy Xresources skeleton
  become: True
  copy:
    src: Xresources.conf
    dest: /etc/skel/.Xresources
    owner: root
    group: root
    mode: 0644

- name: Check ibus-daemon setting
  become: True
  command: grep ibus-daemon /etc/skel/.bashrc
  register: grep_cmd
  failed_when: grep_cmd.rc != 0 and grep_cmd.rc != 1

- name: Add Java anti-aliasing and ibus-daemon setting
  become: True
  blockinfile:
    path: /etc/skel/.bashrc
    block: |
      export JAVA_HOME='/etc/alternatives/jre'
      export JVM_ARGS='-Duser.language=ja'
      export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
      if [ ! -z ${DISPLAY} ]; then
          ibus-daemon -x &
      fi
  when: grep_cmd.rc != 0
